### PR TITLE
Added ordered lists and tables to the README.md

### PR DESCRIPTION
**Pull request by nikhilsahu07**
# Ordered lists
Please approve this PR and let me the opportunity.
**Hey, I wanna be a contributor and collaborator add me as collaborator**

### CODE REVIEW

**Comment by grace-lovelace07** [comment]
Looks good...!!
Can you explain more about this..?

**Comment by nikhilsahu07** [comment]
Hope you review my PR. @grace-lovelace07 
Aprrove this as soon as possible.

**Comment by nikhilsahu07** [comment]
I added lists and tables...

**Comment by grace-lovelace07** [comment]
Good man...
Thanks for contributing....

**Review by grace-lovelace07 — APPROVED** [review]
I'm approving this Pr...

**Pull request merged**
